INSERT INTO LEAGUE VALUES (1,0,30,'PREMIER_LEAGUE');
INSERT INTO LEAGUE VALUES (2,0,10,'LIGUE_1');
INSERT INTO LEAGUE VALUES (3,0,8,'LA_LIGA');
INSERT INTO LEAGUE VALUES (4,0,16,'BUNDESLIGA');
INSERT INTO LEAGUE VALUES (5,0,20,'SERIEA');
INSERT INTO LEAGUE VALUES (6,0,25,'FORTUNA_1_LIGA');
INSERT INTO LEAGUE VALUES (7,0,12,'CHAMPIONS_LEAGUE');
INSERT INTO LEAGUE VALUES (8,0,40,'LIGA_PORTUGAL');

INSERT INTO TEAM VALUES(1,-)

INSERT INTO MATCH VALUES(1,2,'30/05/2020',2,'DRAW',1,'ARSENAL','')