INSERT INTO LEAGUE VALUES (1,'ENGLAND','PREMIER_LEAGUE');
INSERT INTO LEAGUE VALUES (2,'FRANCE','LIGUE_1');
INSERT INTO LEAGUE VALUES (3,'SPAIN','LA_LIGA');
INSERT INTO LEAGUE VALUES (4,'GERMANY','BUNDESLIGA');
INSERT INTO LEAGUE VALUES (5,'ITALY','SERIEA');
INSERT INTO LEAGUE VALUES (6,'POLAND','FORTUNA_1_LIGA');
INSERT INTO LEAGUE VALUES (7,'EUROPE','CHAMPIONS_LEAGUE');
INSERT INTO LEAGUE VALUES (8,'PORTUGAL','LIGA_PORTUGAL');

INSERT INTO TEAM VALUES(1,'ARSENAL');
INSERT INTO TEAM VALUES(2,'CHELSEA');
INSERT INTO TEAM VALUES(3,'MAN_CITY');
INSERT INTO TEAM VALUES(4,'MAN_UTD');
INSERT INTO TEAM VALUES(5,'LIVERPOOL');

INSERT INTO TEAM VALUES(6,'LYON');
INSERT INTO TEAM VALUES(7,'MARSILLE');
INSERT INTO TEAM VALUES(8,'PSG');
INSERT INTO TEAM VALUES(9,'LORIENT');
INSERT INTO TEAM VALUES(10,'MONACO');

INSERT INTO TEAM VALUES(11,'BARCELONA');
INSERT INTO TEAM VALUES(12,'REAL_MADRID');
INSERT INTO TEAM VALUES(13,'ATLETICO_MADRID');
INSERT INTO TEAM VALUES(14,'ATLETIC_BILBAO');
INSERT INTO TEAM VALUES(15,'CELTA_VIGO');

INSERT INTO TEAM VALUES(16,'DORTMUND');
INSERT INTO TEAM VALUES(17,'BAYERN_MUNICH');
INSERT INTO TEAM VALUES(18,'BAYER_LEVERKUSEN');
INSERT INTO TEAM VALUES(19,'MAINZ');
INSERT INTO TEAM VALUES(20,'RB_LEIPZG');

INSERT INTO TEAM VALUES(21,'INTER');
INSERT INTO TEAM VALUES(22,'AC_MILAN');
INSERT INTO TEAM VALUES(23,'JUVENTUS');
INSERT INTO TEAM VALUES(24,'NAPOLI');
INSERT INTO TEAM VALUES(25,'GENOA');

INSERT INTO TEAM VALUES(26,'LEGIA_WARSZAWA');
INSERT INTO TEAM VALUES(27,'JAGIELLONIA_BIALYSTOK');
INSERT INTO TEAM VALUES(28,'LECH_POZNAN');
INSERT INTO TEAM VALUES(29,'SLASK_WROCLAW');
INSERT INTO TEAM VALUES(30,'TERMALICA');

INSERT INTO TEAM VALUES(31,'PORTO');
INSERT INTO TEAM VALUES(32,'BENFICA');
INSERT INTO TEAM VALUES(33,'BRAGA');
INSERT INTO TEAM VALUES(34,'VIZELA');
INSERT INTO TEAM VALUES(35,'ESTORIL');

INSERT INTO USER VALUES(1,'m.rach@vp.pl','Mateusz','Rachubka','chrupek','dgydaskgfj','USER');
INSERT INTO USER VALUES(2,'mat.rachubek@vp.pl','Adam','Iwanowski','iwan','addas','USER');
INSERT INTO USER VALUES(3,'macion.ra@vp.pl','Krystian','Wszywka','wszywek','dgydaaasdskgfj','USER');
INSERT INTO USER VALUES(4,'macrach@vp.pl','Kacper','Koziol','kacpyr','dgydasssdkgfj','USER');
INSERT INTO USER VALUES(5,'m.raoplh@vp.pl','Marek','Dzidek','dzida','dgydasdkgfj','USER');

INSERT INTO MATCH VALUES(1,2,'2021-05-10',2,'DRAW',1,1,2);
INSERT INTO MATCH VALUES(3,1,'2021-05-10',2,'HOME',1,3,4);
INSERT INTO MATCH VALUES(5,2,'2021-08-14',2,'DRAW',1,6,7);
INSERT INTO MATCH VALUES(7,0,'2021-03-02',1,'HOME',1,8,9);
INSERT INTO MATCH VALUES(9,3,'2021-01-11',0,'AWAY',1,11,12);
INSERT INTO MATCH VALUES(11,5,'2021-10-19',2,'AWAY',1,13,14);
INSERT INTO MATCH VALUES(13,2,'2021-11-10',1,'AWAY',1,16,17);
INSERT INTO MATCH VALUES(15,1,'2021-03-15',0,'AWAY',1,18,19);
INSERT INTO MATCH VALUES(17,2,'2021-09-20',3,'HOME',1,21,22);
INSERT INTO MATCH VALUES(19,0,'2021-12-01',2,'HOME',1,23,24);

INSERT INTO CUSTOM_LEAGUE VALUES(1,0,20,1);
INSERT INTO CUSTOM_LEAGUE VALUES(2,0,10,2);
INSERT INTO CUSTOM_LEAGUE VALUES(3,0,15,3);
INSERT INTO CUSTOM_LEAGUE VALUES(4,0,10,4);
INSERT INTO CUSTOM_LEAGUE VALUES(5,0,30,5);
INSERT INTO CUSTOM_LEAGUE VALUES(6,0,30,6);
INSERT INTO CUSTOM_LEAGUE VALUES(7,0,50,7);
INSERT INTO CUSTOM_LEAGUE VALUES(8,0,10,8);

INSERT INTO TEAM_LEAGUE VALUES(1,1);
INSERT INTO TEAM_LEAGUE VALUES(6,2);
INSERT INTO TEAM_LEAGUE VALUES(11,3);
INSERT INTO TEAM_LEAGUE VALUES(16,4);
INSERT INTO TEAM_LEAGUE VALUES(21,5);
INSERT INTO TEAM_LEAGUE VALUES(26,6);

INSERT INTO USER_CUSTOM_LEAGUE VALUES(1,3,1,1);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(2,3,2,1);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(3,1,3,1);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(4,0,4,1);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(5,1,5,1);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(6,1,6,1);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(7,1,7,1);

INSERT INTO USER_CUSTOM_LEAGUE VALUES(8,3,8,2);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(9,3,9,2);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(10,1,10,2);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(11,0,11,2);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(12,1,12,2);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(13,1,13,2);
INSERT INTO USER_CUSTOM_LEAGUE VALUES(14,1,14,2);

INSERT INTO TIPS VALUES(1,2,2,0,1,1,1);
INSERT INTO TIPS VALUES(2,2,1,0,2,2,1);
INSERT INTO TIPS VALUES(3,2,0,0,3,3,1);
INSERT INTO TIPS VALUES(4,2,1,0,2,4,1);
INSERT INTO TIPS VALUES(5,2,0,0,3,5,1);
INSERT INTO TIPS VALUES(6,2,2,0,2,6,1);
INSERT INTO TIPS VALUES(7,2,2,0,3,7,1);
INSERT INTO TIPS VALUES(8,2,2,0,1,8,1);
INSERT INTO TIPS VALUES(9,2,2,0,5,9,1);
INSERT INTO TIPS VALUES(10,2,2,0,1,10,1);